#' @name example_movement_data.csv
#'
#' @title Example movement data file (delimited text)
#'
#' @description
#' A fully synthetic livestock movement data file, created to serve as example
#' input to movenet's `reformat_data()` function. It is inspired by and includes
#' data fields typically found in ScotEID's Scottish pig movement datasets.
#'
#' @format
#' A UTF-8-encoded, comma-separated (csv) text file with 5,001 rows (incl. 1
#' header row) and 19 columns:
#' \describe{
#'   \item{movement_reference}{Unique numeric identifier of the movement.}
#'   \item{foreign_reference, lot_no}{Additional identifiers (character strings).}
#'   \item{lot_date}{Date at which `lot_no` was assigned, using DD/MM/YYYY
#'   format (readr date format specification `%d/%m/%Y`).}
#'   \item{departure_date, arrival_date}{Movement dates, using YYYYMMDD format
#'   (readr date format specification `%Y%m%d`). Either column can be used as the
#'   `date` data field, required in movenet-format movement data.}
#'   \item{qty_pigs}{Movement weight/quantity (number of pigs moved). This
#'   column corresponds to the `weight` data field, required in movenet-format
#'   movement data.}
#'   \item{qty_doa}{Number of pigs dead on arrival.}
#'   \item{fci_declaration}{Food chain information declaration (numeric).}
#'   \item{dep_assurance_no}{A numeric assurance identifier of the originating
#'   keeper or holding.}
#'   \item{dep_name, dep_address, dep_postcode}{Additional identifiers
#'   (character strings) of the originating keeper or holding.}
#'   \item{departure_cph}{Unique identifier of the originating holding; a
#'   character string in the format of a UK County Parish Holding (CPH) number,
#'   This column corresponds to the `from` data field, required in movenet-
#'   format movement data.}
#'   \item{dest_assurance_no}{A numeric assurance identifier of the destination
#'   keeper or holding.}
#'   \item{dest_name, dest_address, dest_postcode}{Additional identifiers
#'   (character strings) of the destination keeper or holding.}
#'   \item{dest_cph}{Unique identifier of the destination holding; a character
#'   string in the format of a UK County Parish Holding (CPH) number. This column
#'   corresponds to the `to` data field, required in movenet-format movement
#'   data.}
#'   }
#'
#' @source
#' The content of this dataset was generated by random number and text
#' generation, using UK-inspired data formats (e.g. County Parish Holding (CPH)
#' identifiers). It does not correspond to or derive from any real movement data.
#'
#' @family example data files and structures
NULL

#' @name example_holding_data.csv
#'
#' @title Example holding data file (delimited text)
#'
#' @description
#' A fully synthetic livestock holding data file, created to serve as example
#' input to movenet's `reformat_data()` function.
#'
#' @format
#' A UTF-8-encoded, comma-separated (csv) text file with 501 rows (incl. 1 header
#' row) and 7 columns:
#' \describe{
#'   \item{cph}{Unique holding identifier; a character string in the format of
#'   a UK County Parish Holding (CPH) number. This column corresponds to the
#'   `id` data field, required in movenet-format holding data.}
#'   \item{extra_column}{Numeric data column, using `.` as decimal mark.}
#'   \item{easting, northing}{Holding coordinates (easting and northing) in an
#'   all-numeric format (assumed to use the British National Grid projection).
#'   These columns correspond to the `coord_x` and `coord_y` data fields,
#'   optional in movenet-format holding data.}
#'   \item{holding_type}{Type of holding (character string). This column
#'   corresponds to the `type` data field, optional in movenet-format holding
#'   data.}
#'   \item{herd_size}{Herd size (numeric). This column corresponds to the
#'   `herd_size` data field, optional in movenet-format holding data.}
#'   }
#'
#' @source
#' The content of this dataset was generated by random number and text
#' generation, using UK-inspired data formats (e.g. County Parish Holding (CPH)
#' identifiers). It does not correspond to or derive from any real holding data.
#'
#' @family example data files and structures
NULL

#' Example movenet-format movement data
#'
#' A fully synthetic livestock movement dataset, created to illustrate the
#' structure of movenet-format movement data tibbles.
#'
#' @format
#' A data frame (tibble) with 5,000 rows and 5 columns:
#' \describe{
#'   \item{departure_cph}{Unique identifier of the holding where the movement
#'   originates; a character string in the format of a UK County Parish Holding
#'   (CPH) number. This column corresponds to the `from` data field, required in
#'   movenet-format movement data.}
#'   \item{dest_cph}{Unique identifier of the holding where the movement is
#'   destined for; a character string in the format of a UK County Parish
#'   Holding (CPH) number. This column corresponds to the `to` data field,
#'   required in movenet-format movement data.}
#'   \item{departure_date}{Movement date, using the R Date class. This column
#'   corresponds to the `date` data field, required in movenet-format movement
#'   data.}
#'   \item{qty_pigs}{Movement weight/quantity (number of pigs moved), in numeric
#'   (double) format. This column corresponds to the `weight` data field,
#'   required in movenet-format movement data.}
#'   \item{movement_reference}{A movement reference number. This column
#'   illustrates an optional data field in movenet-format movement data.}
#'   }
#'
#' @source
#' The content of this dataset was generated by random number and text
#' generation, using UK-inspired data formats (e.g. County Parish Holding (CPH)
#' identifiers). It does not correspond to or derive from any real movement data.
#'
#' The csv-format data file that this movement data tibble was derived from
#' is accessible at
#' `system.file("extdata/example_movement_data.csv", package = "movenet")`. The
#' tibble was obtained by calling `reformat_data()` on this csv file.
#'
#' @family example data files and structures
#' @seealso `vignette("movenet")` for a detailed illustration of how this tibble
#' was obtained from `example_movement_data.csv`.
"example_movement_data"

#' Example movenet-format holding data
#'
#' A fully synthetic livestock holding dataset, created to illustrate the
#' structure of movenet-format holding data tibbles.
#'
#' @format
#' A data frame (tibble) with 500 rows and 4 columns:
#' \describe{
#'   \item{cph}{Unique holding identifier; a character string in the format of
#'   a UK County Parish Holding (CPH) number. This column corresponds to the
#'   `id` data field, required in movenet-format holding data.}
#'   \item{holding_type}{Type of holding (character string). This column
#'   corresponds to the `type` data field, optional in movenet-format holding
#'   data.}
#'   \item{herd_size}{Herd size, in numeric (double) format. This column
#'   corresponds to the `herd_size` data field, optional in movenet-format
#'   holding data.}
#'   \item{coordinates}{Holding coordinates in degrees longitude and latitude,
#'   using the ETRS89 coordinate reference system, and formated as a simple
#'   feature (sf) geometry list-column (class `sfc_POINT`). This column is
#'   derived from `coord_x` and `coord_y` data fields, optional in
#'   movenet-format holding data.}
#'   }
#'
#' @source
#' The content of this dataset was generated by random number and text
#' generation, using UK-inspired data formats (e.g. County Parish Holding (CPH)
#' identifiers). It does not correspond to or derive from any real holding data.
#'
#' The csv-format data file that this holding data tibble was derived from
#' is accessible at
#' `system.file("extdata/example_holding_data.csv", package = "movenet")`. The
#' tibble was obtained by calling `reformat_data()` on this csv file.
#'
#' @family example data files and structures
#' @seealso `vignette("movenet")` for a detailed illustration of how this tibble
#' was obtained from `example_holding_data.csv`.
"example_holding_data"

#' ASF local spread transmission probabilities
#'
#' @description
#' Look-up table with daily probabilities of a susceptible holding becoming
#' infected with African swine fever through local spread, based on distance
#' from an infectious holding. Given as four distinct distance bands with
#' positive probabilities (indicating potential transmission) for distances up
#' to 2 km, and a band with probability 0 for distances >= 2 km. Local spread is
#' deemed to include, for example, transmission via rodents and insects,
#' unregistered animal movements, and sharing of equipment and tools.
#'
#' Reference: Halasa, T. *et al.* (2016). Simulating the epidemiological and
#' economic effects of an African swine fever epidemic in industrialized swine
#' populations. *Veterinary Microbiology*, *193*, 7-16.
#' <https://doi.org/10.1016/j.vetmic.2016.08.004>
#'
#' @format
#' A data frame (tibble) with 5 rows and 3 columns:
#' \describe{
#'   \item{lower_boundary}{Lower boundary of each distance band (inclusive),
#'   in meters.}
#'   \item{upper_boundary}{Upper boundary of each distance band (exclusive),
#'   in meters.}
#'   \item{probability}{Daily probability of infection through local spread,
#'   given a distance from an infectious holding between `lower_boundary` and
#'   `upper_boundary`.}
#'   }
#'
#' @source Halasa, T. *et al.* (2016). Simulating the epidemiological and
#' economic effects of an African swine fever epidemic in industrialized swine
#' populations. *Veterinary Microbiology*, *193*, 7-16.
#' <https://doi.org/10.1016/j.vetmic.2016.08.004>
#'
#' @family example data files and structures
"local_spread_probabilities_ASF"


